services:
  - type: web
    name: bizur-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
    healthCheckPath: /
